### ISSUE TITLE
Bug: Spacing between words in tables (Firefox and Safari on Mac only)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#195] opened 2021-06-25 23:13 UTC
Let's divide the content pages amongst the team and do an audit for words running together. See screenshot

![Screen Shot 2021-06-25 at 4 12 37 PM](https://user-images.githubusercontent.com/1387973/123493052-2d9b5300-d5d0-11eb-979e-fe0fde0b29b0.png)

**Comment by m-sullivan7** [comment] 2021-06-28 17:04
[Google Sheet for review](https://docs.google.com/spreadsheets/d/1QVq3KKQ60FxmGR8c5Eq60GW2FUfUUP8hxxUfT7QPtXE/edit?usp=sharing) created.

Interestingly, when I went to the _Grant funding_ page where this content lives, I didn't see the spacing error in the screenshot. I checked the code editor view of the page and did not see anything amiss. Do we know what browser/device was used when reporting that error @wrendo ?

**Comment by m-sullivan7** [comment] 2021-06-29 18:21
@wrendo I've resolved all the spacing errors reported in the Google Sheet with one exception: on [Scientific research](https://staginginye.prod3.sites.ca.gov/about-us/scientific-research/) Ada reported that _Public university_ in the table header inside the _2020_ accordion didn't have a space. I've checked WordPress and confirmed that there is one. I see the space on Firefox desktop on PC. Ada and I looked together an Firefox desktop on Mac, as well as Safari desktop on Mac, doesn't show a space (Chrome desktop on Mac does show the space). It looks like there's a browser-specific bug for engineering.

This feels like work that should spin off into another ticket and we should close this ticket, which was focused on content fixes to spacing. Do you agree?

**Closed** 2021-07-08 00:15 UTC
Labels: 2 pts, Low Priority - Non-critical, Post Launch, QA
