### ISSUE TITLE
Editor UX: Entire column creation UX is confusing

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#204] opened 2021-06-28 00:42 UTC
Need to discuss on how to improve.

**Comment by chachasikes** [comment] 2021-09-07 17:00
Agree - we will check WordPress 5.8, and their complaint log - and then we can research alternatives.

**Comment by chachasikes** [comment] 2021-11-09 16:47
Duplicate of #205, closing.

**Closed by chachasikes** 2021-11-09 16:47 UTC
Labels: Low Priority - Non-critical
