### ISSUE TITLE
Editor Bug: Creating columns from within paragraph block broken

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#203] opened 2021-06-28 00:40 UTC
Choosing to turn a paragraph into a column does nothing.

**Comment by chachasikes** [comment] 2021-09-07 17:07
We should not be creating columns inside p tags, let's revisit where this was happening - may be a different contextual issue - or training.

The block tools will get used in creative ways, we do limit some capabilities in some contexts (vs. others) - and some block elements limit who their children can be.

**Comment by chachasikes** [comment] 2021-11-09 16:48
Duplicate of #205 (general column issue), closing

**Closed by chachasikes** 2021-11-09 16:48 UTC
Labels: Low Priority - Non-critical
